const express = require('express');
const router = express.Router();
const desercionController = require('../controllers/desercionController');
const auth = require('../middleware/auth');

router.get('/', auth, desercionController.obtenerDesercion);
router.get('/estadistica', auth, desercionController.obtenerEstadisticaDesercionPorPeriodo);
router.get('/estadistica-facultad', auth, desercionController.obtenerEstadisticaDesercionPorFacultad);
router.get('/estadistica-programa', auth, desercionController.obtenerEstadisticaDesercionPorPrograma);
router.get('/estadistica-nivel', auth, desercionController.obtenerEstadisticaDesercionPorNivel);
router.get('/programas', auth, desercionController.obtenerProgramas);
router.get('/cohorte', auth, desercionController.obtenerDesertoresCohorte);
router.get('/ausencia-intersemestral', (req, res, next) => {
  console.log('[RUTA] Petición recibida en /ausencia-intersemestral');
  console.log('[RUTA] Query params:', req.query);
  next();
}, auth, desercionController.obtenerAusenciaIntersemestral);
router.get('/ausencia-intersemestral/estadistica', auth, desercionController.obtenerEstadisticaAusenciaPorPeriodo);
router.get('/ausencia-intersemestral/estadistica-facultad', auth, desercionController.obtenerEstadisticaAusenciaPorFacultad);
router.get('/ausencia-intersemestral/estadistica-programa', auth, desercionController.obtenerEstadisticaAusenciaPorPrograma);
router.get('/ausencia-intersemestral/estadistica-nivel', auth, desercionController.obtenerEstadisticaAusenciaPorNivel);
router.get('/tasa-desercion/estadistica-periodo', auth, desercionController.obtenerTasaDesercionPorPeriodo);
router.get('/tasa-desercion/estadistica-facultad', auth, desercionController.obtenerTasaDesercionPorFacultad);
router.get('/tasa-desercion/estadistica-programa', auth, desercionController.obtenerTasaDesercionPorPrograma);
router.get('/tasa-desercion/estadistica-nivel', auth, desercionController.obtenerTasaDesercionPorNivel);
router.get('/tasa-desercion-cohorte/estadistica-periodo', auth, desercionController.obtenerTasaDesercionCohortePorPeriodo);
router.get('/tasa-desercion-cohorte/estadistica-facultad', auth, desercionController.obtenerTasaDesercionCohortePorFacultad);
router.get('/tasa-desercion-cohorte/estadistica-programa', auth, desercionController.obtenerTasaDesercionCohortePorPrograma);
router.get('/tasa-desercion-cohorte/estadistica-nivel', auth, desercionController.obtenerTasaDesercionCohortePorNivel);
router.get('/tasa-desercion-promedio/estadistica-periodo', auth, desercionController.obtenerTasaDesercionPromedioPorPeriodo);
router.get('/tasa-desercion-promedio/estadistica-facultad', auth, desercionController.obtenerTasaDesercionPromedioPorFacultad);
router.get('/tasa-desercion-promedio/estadistica-programa', auth, desercionController.obtenerTasaDesercionPromedioPorPrograma);
router.get('/tasa-desercion-promedio/estadistica-nivel', auth, desercionController.obtenerTasaDesercionPromedioPorNivel);
router.get('/tasa-graduacion/estadistica-periodo', auth, desercionController.obtenerTasaGraduacionPorPeriodo);
router.get('/tasa-graduacion/estadistica-facultad', auth, desercionController.obtenerTasaGraduacionPorFacultad);
router.get('/tasa-graduacion/estadistica-programa', auth, desercionController.obtenerTasaGraduacionPorPrograma);
router.get('/tasa-graduacion/estadistica-nivel', auth, desercionController.obtenerTasaGraduacionPorNivel);
router.get('/tasa-ausencia-intersemestral/estadistica-periodo', auth, desercionController.obtenerTasaAusenciaPorPeriodo);
router.get('/tasa-ausencia-intersemestral/estadistica-facultad', auth, desercionController.obtenerTasaAusenciaPorFacultad);
router.get('/tasa-ausencia-intersemestral/estadistica-programa', auth, desercionController.obtenerTasaAusenciaPorPrograma);
router.get('/tasa-ausencia-intersemestral/estadistica-nivel', auth, desercionController.obtenerTasaAusenciaPorNivel);
router.get('/tasa-supervivencia/estadistica-periodo', auth, desercionController.obtenerTasaSupervivenciaPorPeriodo);
router.get('/tasa-supervivencia/estadistica-facultad', auth, desercionController.obtenerTasaSupervivenciaPorFacultad);
router.get('/tasa-supervivencia/estadistica-programa', auth, desercionController.obtenerTasaSupervivenciaPorPrograma);
router.get('/tasa-supervivencia/estadistica-nivel', auth, desercionController.obtenerTasaSupervivenciaPorNivel);
router.get('/tasa-desercion-periodo-2-8/estadistica-periodo', auth, desercionController.obtenerTasaDesercion28PorPeriodo);
router.get('/tasa-desercion-periodo-2-8/estadistica-facultad', auth, desercionController.obtenerTasaDesercion28PorFacultad);
router.get('/tasa-desercion-periodo-2-8/estadistica-programa', auth, desercionController.obtenerTasaDesercion28PorPrograma);
router.get('/tasa-desercion-periodo-2-8/estadistica-nivel', auth, desercionController.obtenerTasaDesercion28PorNivel);
router.post('/predict', auth, desercionController.predecirDesercion);
router.get('/riesgo-desercion', auth, desercionController.obtenerRiesgoDesercion);

module.exports = router; 